version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - APPSETTING_DBPROVIDERNAME=MySql.Data.MySqlClient
      - APPSETTING_DBCONNECTION=server=mysql; port=3306; database=step; userid=user; password=user;
      - APPSETTING_REDISCONNECTION=redis,allowAdmin=true
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - mysql
      - redis

  adminer:
    image: adminer:4.7.7
    container_name: adminer
    ports:
      - "9000:8080"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0.21
    container_name: db
    restart: always
    volumes:
      - ./_DockerForDevelopment/mysql/conf.d:/etc/mysql/conf.d
      - ./_DockerForDevelopment/mysql/initsql:/docker-entrypoint-initdb.d
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: !!str yes
      MYSQL_DATABASE: step
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: "Asia/Tokyo"

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redisvol:/data
    ports:
      - "6379:6379"

volumes:
  dbvol:
  redisvol:
