CREATE TABLE News (
    NewsId INT NOT NULL
,   Title VARCHAR(128) NOT NULL
,   Body VARCHAR(8192) NOT NULL
,   FromDate DATETIME NOT NULL
,   ToDate DATETIME NOT NULL
,   AddTime DATETIME NOT NULL
,   UpdTime DATETIME NOT NULL
,   PRIMARY KEY (NewsId)
);
